POST http://localhost:5000/moonlet-beta/us-central1/push/new
Content-Type: application/json

{
    "bridge": "https://bridge.walletconn",
    "topic": "c50901f1-ca34-44da-9c8b-4a79e0cbbd11",
    "type": "fcm",
    "token": "123asd",
    "peerName": "<peer_name>",
    "language": "<language_code>"
}

###

POST http://localhost:5000/moonlet-beta/us-central1/push
Content-Type: application/json

{
    "topic": "c50901f1-ca34-44da-9c8b-4a79e0cbbd11"
}